[toolchain]
anchor_version = "0.32.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rentx = "H8dxbPQhNTmDiJwpJPGeJ3QnA8zaYsYGHv1yumysws8k"

[programs.devnet]
rentx = "H8dxbPQhNTmDiJwpJPGeJ3QnA8zaYsYGHv1yumysws8k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_PATH=../tests/node_modules TS_NODE_TRANSPILE_ONLY=true ../tests/node_modules/.bin/ts-mocha -p ../tests/tsconfig.json -t 1000000 '../tests/*.ts'"
